import { useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, FileCheck2, Loader2, ShieldCheck, Store, UploadCloud } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";

export default function Partners() {
  const { lang } = useLanguage();
  const ar = lang === "ar";
  const Arrow = ar ? ArrowLeft : ArrowRight;
  const [sending, setSending] = useState(false);
  const [notice, setNotice] = useState<{ ok: boolean; text: string }>();
  const t = ar ? {
    tag: "شركاء المنتجات الرقمية", title: "منتجك يستحق متجرًا يحميه ويقدمه باحتراف", intro: "قدّم منتجك للمراجعة. نقبل المنتجات الأصلية ذات القيمة الواضحة، ولا ننشر أي ملف مباشرة قبل التحقق من الجودة والحقوق.",
    steps: [["قدّم المنتج", "أرسل البيانات ورابطًا تجريبيًا خاصًا."], ["مراجعة الجودة والحقوق", "نتحقق من الأصالة والفائدة وتجربة العميل."], ["اتفاق ونشر", "نحدد العمولة والتسوية ثم نجهز صفحة البيع."]],
    accept: "ما الذي نقبله؟", types: ["قوالب وأدوات أعمال", "كتب وأدلة رقمية", "دورات ومواد تعليمية", "تصاميم وحزم محتوى", "أدوات وبرمجيات رقمية"],
    rules: "قبل التقديم", rulesText: "يجب أن تملك حقوق المنتج كاملة. لا نقبل المحتوى المنسوخ أو المسروق أو المنتجات التي تقدم وعودًا مضللة. التقديم لا يعني القبول.",
    form: "طلب الانضمام", formText: "هذه مرحلة مراجعة فقط. لن يُنشر المنتج ولن تُحصّل أي رسوم قبل الاتفاق معك.", name: "الاسم الكامل", email: "البريد الإلكتروني", phone: "رقم الجوال", brand: "اسم العلامة أو المتجر", type: "نوع المنتج", choose: "اختر نوع المنتج", link: "رابط معاينة خاص", price: "السعر المقترح بالريال", description: "اشرح المنتج والفائدة التي يقدمها", rights: "أؤكد أنني أملك حقوق بيع هذا المنتج", submit: "إرسال طلب الشراكة", sending: "جارٍ الإرسال...", success: "استلمنا طلبك. سنراجعه ونتواصل معك إذا كان مناسبًا للمتجر.", error: "تعذر إرسال الطلب. تحقق من البيانات وحاول مرة أخرى.", privacy: "بياناتك ورابط المعاينة تُستخدم للمراجعة فقط.",
  } : {
    tag: "DIGITAL PRODUCT PARTNERS", title: "Your product deserves a store that protects and presents it professionally", intro: "Submit your product for review. We accept original products with clear value and never publish a file before quality and rights checks.",
    steps: [["Submit", "Share the essentials and a private preview link."], ["Quality & rights review", "We verify originality, value, and customer experience."], ["Agree & publish", "We set commission and settlement terms, then build the sales page."]],
    accept: "What we accept", types: ["Business templates and tools", "E-books and digital guides", "Courses and learning materials", "Design and content packs", "Digital tools and software"],
    rules: "Before applying", rulesText: "You must own all rights to the product. We reject copied, stolen, or misleading products. Applying does not guarantee acceptance.",
    form: "Partner application", formText: "This is a review stage only. Nothing is published and no fee is charged before an agreement.", name: "Full name", email: "Email", phone: "Phone", brand: "Brand or store name", type: "Product type", choose: "Select product type", link: "Private preview link", price: "Suggested price in SAR", description: "Explain the product and the value it provides", rights: "I confirm that I own the rights to sell this product", submit: "Send partner application", sending: "Sending...", success: "We received your application. We will review it and contact you if it fits the store.", error: "We could not send the application. Check the details and retry.", privacy: "Your details and preview link are only used for review.",
  };

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setSending(true); setNotice(undefined); const form = e.currentTarget;
    try {
      const res = await fetch("/api/partner-application", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), lang }) });
      if (!res.ok) throw new Error();
      setNotice({ ok: true, text: t.success }); form.reset();
    } catch { setNotice({ ok: false, text: t.error }); } finally { setSending(false); }
  }

  return <main className="min-h-screen bg-[#f5f7fb] text-slate-950">
    <section className="relative overflow-hidden bg-[#070b13] pb-20 pt-32 text-white md:pb-28 md:pt-40"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(37,99,235,.25),transparent_30%),radial-gradient(circle_at_80%_75%,rgba(124,58,237,.18),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-black tracking-[.18em] text-blue-400">{t.tag}</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight sm:text-5xl lg:text-6xl">{t.title}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{t.intro}</p><button onClick={() => document.getElementById("apply")?.scrollIntoView({ behavior: "smooth" })} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-7 py-4 font-black hover:bg-blue-500">{t.form}<Arrow className="h-5 w-5" /></button></div><div className="overflow-hidden rounded-[2rem] border border-white/10 p-2 shadow-2xl"><img src="/images/digzoom/creator-partner-live.webp" alt={ar ? "شريكة تصنع منتجًا رقميًا" : "Creator building a digital product"} className="aspect-[16/11] w-full rounded-[1.5rem] object-cover" /></div></div></section>
    <section className="py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{t.steps.map(([title, text], i) => <div key={title} className="rounded-3xl border border-slate-200 bg-white p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 font-black text-blue-600">0{i + 1}</span><h2 className="mt-6 text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-slate-500">{text}</p></div>)}</div></div></section>
    <section className="pb-24"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-[2rem] bg-white p-8 shadow-sm"><Store className="h-8 w-8 text-blue-600" /><h2 className="mt-5 text-3xl font-black">{t.accept}</h2><ul className="mt-7 space-y-4">{t.types.map(x => <li key={x} className="flex items-center gap-3 font-bold"><CheckCircle2 className="h-5 w-5 text-emerald-600" />{x}</li>)}</ul></div><div className="rounded-[2rem] bg-slate-950 p-8 text-white"><ShieldCheck className="h-8 w-8 text-violet-400" /><h2 className="mt-5 text-3xl font-black">{t.rules}</h2><p className="mt-6 text-lg leading-8 text-slate-300">{t.rulesText}</p></div></div></section>
    <section id="apply" className="scroll-mt-24 bg-[#eef3ff] py-24"><div className="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><div><p className="text-sm font-black tracking-[.18em] text-blue-600">{t.tag}</p><h2 className="mt-4 text-4xl font-black">{t.form}</h2><p className="mt-5 leading-8 text-slate-600">{t.formText}</p><div className="mt-8 flex items-center gap-3 rounded-2xl bg-white p-5 text-sm font-bold text-slate-600"><FileCheck2 className="h-6 w-6 text-emerald-600" />{t.privacy}</div></div>
      <form onSubmit={submit} className="rounded-[2rem] bg-white p-6 shadow-xl sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><Field label={t.name}><input name="name" required maxLength={100} /></Field><Field label={t.email}><input name="email" type="email" required maxLength={200} dir="ltr" /></Field><Field label={t.phone}><input name="phone" required maxLength={30} dir="ltr" /></Field><Field label={t.brand}><input name="brand" maxLength={120} /></Field><Field label={t.type}><select name="product_type" required defaultValue=""><option value="" disabled>{t.choose}</option>{t.types.map(x => <option key={x}>{x}</option>)}</select></Field><Field label={t.price}><input name="suggested_price" type="number" min="0" max="100000" /></Field><Field label={t.link} wide><input name="preview_url" type="url" required maxLength={500} dir="ltr" placeholder="https://" /></Field><Field label={t.description} wide><textarea name="description" required rows={5} maxLength={2000} /></Field></div><label className="mt-5 flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm font-bold"><input name="rights_confirmed" value="true" type="checkbox" required className="mt-1 h-4 w-4" />{t.rights}</label>{notice && <div role="status" className={`mt-5 rounded-xl p-4 text-sm ${notice.ok ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{notice.text}</div>}<button disabled={sending} className="mt-6 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 font-black text-white hover:bg-blue-500 disabled:opacity-60">{sending ? <><Loader2 className="h-5 w-5 animate-spin" />{t.sending}</> : <><UploadCloud className="h-5 w-5" />{t.submit}</>}</button></form>
    </div></section>
  </main>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) {
  return <label className={`text-sm font-bold text-slate-700 ${wide ? "sm:col-span-2" : ""}`}><span>{label}</span><div className="mt-2 [&>input]:h-12 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-slate-200 [&>input]:px-4 [&>select]:h-12 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-slate-200 [&>select]:px-4 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-slate-200 [&>textarea]:p-4">{children}</div></label>;
}
