import {useEffect,useState,type FormEvent} from 'react';
import {Link} from 'react-router';
import {Store,Plus,Wallet,Package,Copy,RefreshCw} from 'lucide-react';
import {useSupabaseAuth} from '@/hooks/useSupabaseAuth';
import {merchantApi,money,partnerStatus} from '@/lib/merchant-api';
export default function PartnerDashboard(){
 const {user,loading}=useSupabaseAuth();const [data,setData]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<any>(null),[open,setOpen]=useState(false);
 async function load(){try{setData(await merchantApi());setError('');}catch(e:any){setError(e.message);}}
 useEffect(()=>{if(user)void load();},[user?.id]);
 async function act(body:any){setBusy(true);setError('');try{await merchantApi(body);await load();return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));if(await act({action:'save_offer',id:edit?.id,offer:{...fields,rights_confirmed:true}})){setOpen(false);setEdit(null);}}
 const box='rounded-2xl border border-slate-200 bg-white p-5 sm:p-7';
 if(loading)return <main className="min-h-screen pt-36 text-center">جارٍ التحميل…</main>;
 if(!user)return <main dir="rtl" className="min-h-screen bg-slate-50 px-5 pb-20 pt-36 text-center"><h1 className="text-3xl font-black">لوحة التاجر</h1><p className="my-6">سجّل الدخول بحسابك لتقديم طلب الشراكة ومتابعته.</p><Link className="rounded-xl bg-blue-600 px-6 py-3 text-white" to="/login">تسجيل الدخول</Link></main>;
 const merchant=data?.merchant, items=data?.items||[];
 const eligible=items.filter((i:any)=>i.status==='ready'&&i.delivered_at&&new Date(i.ready_at).getTime()<=Date.now());
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fb] px-4 pb-20 pt-28 text-slate-900 sm:pt-36"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold text-blue-600">بع منتجاتك معنا</p><h1 className="mt-2 text-3xl font-black">لوحة التاجر</h1><p className="mt-3 text-slate-500">عروضك وطلباتك ومستحقاتك، في مكان واحد.</p></div><button onClick={load} aria-label="تحديث" className="rounded-xl border bg-white p-3"><RefreshCw size={20}/></button></header>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
 {!data&&!error&&<p>جارٍ تحميل البيانات…</p>}
 {data&&!merchant&&<section className={box}><Store className="text-blue-600"/><h2 className="mt-4 text-xl font-black">{data.application?partnerStatus[data.application.status]:'ابدأ شراكتك مع DigZoom'}</h2><p className="my-4 text-slate-600">{data.application?'اعتماد الحساب بيد الإدارة بعد مراجعة الحقوق والشروط.':'قدّم طلبك؛ بعد الاعتماد تقدر ترفع عروضك وتتابع طلباتك.'}</p><Link to="/partners#apply" className="font-bold text-blue-600">صفحة الشراكة ←</Link></section>}
 {merchant&&<><section className={box}><span className="rounded-full bg-blue-50 px-3 py-1 font-bold text-blue-700">{partnerStatus[merchant.status]}</span><p className="mt-4 text-slate-600">المنتجات تُعرض باسم DigZoom. بيانات هويتك خاصة بك وبالإدارة.</p><div className="mt-4 flex flex-wrap items-center gap-3"><code dir="ltr" className="min-w-0 break-all rounded-lg bg-slate-50 p-3 text-sm">{`${window.location.origin}/api/merchant?ref=${merchant.referral_code}`}</code><button onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/api/merchant?ref=${merchant.referral_code}`);setError('تم نسخ رابطك');}catch{setError('انسخ الرابط الظاهر يدويًا');}}} className="inline-flex items-center gap-2 font-bold text-blue-600"><Copy size={17}/>نسخ رابط 15%</button></div><p className="mt-3 text-sm leading-6 text-slate-500">نسبة رابطك 15% على منتجاتك خلال 7 أيام من زيارة العميل؛ طلبات DigZoom بنسبة 25% تشمل إدارة التسويق ضمن ميزانيتها، دون ضمان عدد مبيعات.</p></section>
 <div className="grid gap-4 sm:grid-cols-3">{[[<Package key="p"/>, 'العروض',data.offers.length],[<Wallet key="w"/>,'مستحقات مؤهلة',money(eligible.reduce((s:number,i:any)=>s+Number(i.merchant_cents||0),0))],[<Wallet key="s"/>,'تسويات مسجلة',money(data.settlements.reduce((s:number,i:any)=>s+Number(i.paid_cents),0))]].map(([icon,label,value],i)=><div key={i} className={box}>{icon}<p className="mt-4 text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>
 <section className={box}><h2 className="text-xl font-black">كيف تُحسب مستحقاتك؟</h2><p className="mt-3 leading-7 text-slate-600">قيمة البيع بعد الخصم، دون الضرائب، ناقص رسوم Stripe الفعلية؛ ثم تُحسب العمولة. رسوم التحويل والسحب تُخصم مرة واحدة عند التسوية بالتكلفة الفعلية الموثّقة.</p><p className="mt-3 leading-7 text-slate-600">تسوية يدوية شهرية بعد اعتماد التسليم ومرور {data.settings.hold_days} يومًا من الدفع. الحد الأدنى {money(data.settings.minimum_payout_cents)}. الطلبات المسترجعة والمتنازع عليها معلّقة للمراجعة.</p></section>
 <section className={box}><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">عروضك</h2><button disabled={busy||merchant.status!=='active'} onClick={()=>{setEdit(null);setOpen(!open);}} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-50"><Plus size={18}/>عرض جديد</button></div>
 {open&&<form onSubmit={save} key={edit?.id||'new'} className="mt-6 grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-2">{[['title','اسم المنتج','text'],['price_sar','السعر بالريال (عدد صحيح)','number'],['image_url','رابط صورة المنتج HTTPS','url'],['preview_url','رابط معاينة خاص HTTPS','url']].map(([name,label,type])=><label key={name} className="font-bold">{label}<input className="mt-2 w-full rounded-lg border p-3" name={name} type={type} min={name==='price_sar'?1:undefined} max={name==='price_sar'?100000:undefined} required defaultValue={edit?.[name]||''}/></label>)}<label className="font-bold sm:col-span-2">وصف المنتج<textarea className="mt-2 w-full rounded-lg border p-3" name="description" minLength={30} maxLength={4000} required rows={4} defaultValue={edit?.description||''}/></label><label className="font-bold sm:col-span-2">طريقة ومدة التسليم<textarea className="mt-2 w-full rounded-lg border p-3" name="fulfillment_method" minLength={10} required defaultValue={edit?.fulfillment_method||''}/></label><label className="flex items-start gap-2 sm:col-span-2"><input type="checkbox" required className="mt-1"/>أملك حقوق البيع والتسليم؛ المنتج لا يخالف شروط المنصة، وأوافق على شروط الشراكة.</label><div className="flex flex-wrap gap-3 sm:col-span-2"><button name="status" value="review" disabled={busy} className="rounded-lg bg-blue-600 px-5 py-3 font-bold text-white">إرسال للمراجعة</button><button type="button" disabled={busy} onClick={async(e)=>{const form=e.currentTarget.closest('form')!;if(!form.reportValidity())return;const fields=Object.fromEntries(new FormData(form));if(await act({action:'save_offer',id:edit?.id,offer:{...fields,status:'draft',rights_confirmed:true}}))setOpen(false);}} className="rounded-lg border px-4 py-3">حفظ مسودة</button><button type="button" onClick={()=>setOpen(false)}>إلغاء</button></div></form>}
 <div className="mt-5 space-y-3">{!data.offers.length&&<p className="text-slate-500">لا توجد عروض بعد. ارفع أول منتج للمراجعة.</p>}{data.offers.map((offer:any)=><article key={offer.id} className="flex gap-4 rounded-xl border p-4"><img src={offer.image_url} alt="" className="h-16 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><h3 className="font-bold">{offer.title}</h3><p className="mt-2 text-sm text-slate-500">{money(offer.price_sar*100)} · {partnerStatus[offer.status]}</p>{offer.review_note&&<p className="mt-2 text-sm text-amber-700">{offer.review_note}</p>}</div>{['draft','rejected'].includes(offer.status)&&<button disabled={busy} onClick={()=>{setEdit(offer);setOpen(true);}} className="font-bold text-blue-600">تعديل</button>}</article>)}</div></section>
 <section className={box}><h2 className="text-xl font-black">طلبات المنتجات</h2><p className="mt-3 text-sm text-slate-500">ارفع إثبات التسليم؛ الإدارة تراجعه وتعتمده. بيانات العميل لا تظهر في اللوحة.</p><div className="mt-5 space-y-4">{!items.length&&<p className="text-slate-500">لا توجد طلبات بعد.</p>}{items.map((item:any)=><article key={item.id} className="rounded-xl border p-4"><h3 className="font-bold">{item.product_title} × {item.quantity}</h3><p dir="ltr" className="mt-2 break-all text-xs text-slate-500">{item.order_id}</p><p className="mt-3 text-sm">{partnerStatus[item.status]} · {item.commission_percent}% · {item.source==='merchant'?'من رابطك':'من DigZoom'}</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-4"><p>البيع: {money(item.gross_cents)}</p><p>رسوم الدفع: {money(item.stripe_fee_cents)}</p><p>العمولة: {money(item.commission_cents)}</p><p className="font-bold">مستحقك: {money(item.merchant_cents)}</p></div>{item.hold_reason&&<p className="mt-3 text-amber-700">معلّق: راجع الإدارة لتسوية الاسترجاع أو النزاع.</p>}{item.fulfillment_submitted_at&&<p className="mt-3 text-emerald-700">{item.delivered_at?'التسليم معتمد':'إثبات التسليم بانتظار اعتماد الإدارة'}</p>}{item.paid_at&&!item.delivered_at&&item.status!=='held'&&merchant.status==='active'&&<form className="mt-4 space-y-3" onSubmit={async(e)=>{e.preventDefault();const form=e.currentTarget;const note=String(new FormData(form).get('note')||'');if(await act({action:'fulfill',id:item.id,note}))form.reset();}}><label className="block text-sm font-bold">تفاصيل أو رابط إثبات التسليم<textarea name="note" required minLength={10} maxLength={3000} className="mt-2 w-full rounded-lg border p-3" rows={2}/></label><button disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">إرسال إثبات التسليم</button></form>}</article>)}</div></section>
 <section className={box}><h2 className="text-xl font-black">سجل التسويات</h2>{!data.settlements.length&&<p className="mt-4 text-slate-500">لم تُسجّل تحويلات بعد.</p>}{data.settlements.map((s:any)=><div key={s.id} className="mt-4 rounded-xl border p-4"><p>المستحق: {money(s.gross_cents)} · رسوم التحويل: {money(s.transfer_fee_cents)}</p><p className="mt-2 font-bold">المحوّل: {money(s.paid_cents)}</p><p className="mt-2 break-all text-sm text-slate-500">{s.reference} · {new Date(s.created_at).toLocaleDateString('ar-SA')}</p></div>)}</section></>}
 </div></main>;
}
