import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Link} from 'react-router';
import {ArrowLeft,ArrowRight,Loader2,UploadCloud} from 'lucide-react';
import {useLanguage} from '@/hooks/useLanguage';
import {useSupabaseAuth} from '@/hooks/useSupabaseAuth';
import PreviewFiles,{type PreviewAsset} from '@/components/partners/PreviewFiles';
import PartnerTerms from '@/components/partners/PartnerTerms';
import {PRODUCT_KINDS} from '@/data/partnerFiles';
export default function Partners(){
 const {lang}=useLanguage(),ar=lang==='ar',{user,logout}=useSupabaseAuth(),Arrow=ar?ArrowLeft:ArrowRight;
 const [files,setFiles]=useState<PreviewAsset[]>([]),[uploading,setUploading]=useState(false),[sending,setSending]=useState(false),[notice,setNotice]=useState<{ok:boolean;text:string}>();
 const [contactEmail,setContactEmail]=useState(user?.email||'');
 useEffect(()=>{setContactEmail(user?.email||'');},[user?.id,user?.email]);
 const t=(arabic:string,english:string)=>ar?arabic:english;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user||uploading)return;const form=e.currentTarget;
 if(!files.length){setNotice({ok:false,text:t('ارفع ملفًا واحدًا على الأقل لمعاينة منتجك.','Upload at least one product preview file.')});return;}
 setSending(true);setNotice(undefined);
 try{const response=await fetch('/api/partner-application',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('sb_access_token')||''}`},body:JSON.stringify({...Object.fromEntries(new FormData(form)),preview_asset_ids:files.map(f=>f.id),lang,terms_version:'2026-10-v1'})});const data=await response.json();if(!response.ok)throw new Error(data.error||t('تعذر الإرسال. حاول مرة أخرى.','Could not submit. Please retry.'));
 setNotice({ok:true,text:t('وصل طلبك وملفات المعاينة. تابع حالة الطلب من لوحة التاجر.','Your application and preview files were received. Track the status in your dashboard.')});form.reset();setContactEmail(user?.email||'');setFiles([]);
 }catch(e:any){setNotice({ok:false,text:e.message});}finally{setSending(false);}}
 return <main dir={ar?'rtl':'ltr'} className="min-h-screen bg-[#f5f7fb] text-slate-950"><section className="bg-[#070b13] pb-12 pt-28 text-white sm:pb-16 sm:pt-36"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 sm:px-6 md:grid-cols-2"><div><p className="text-sm font-bold text-blue-400">DigZoom</p><h1 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">{t('بع منتجاتك معنا','Sell your products with us')}</h1><p className="mt-5 text-base leading-7 text-slate-300">{t('عندك كتاب، قالب، فيديو أو تصميم؟ ارفع عينة من منتجك، وخَلّنا نراجعه ونجهّزه للبيع.','Have a book, template, video or design? Upload a sample for review and let us prepare it for sale.')}</p><div className="mt-6 flex flex-wrap gap-3"><a href="#apply" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold">{t('قدّم منتجك','Submit your product')}<Arrow size={18}/></a><Link to="/partner-dashboard" className="rounded-xl border border-white/20 px-5 py-3 font-bold">{t('لوحة التاجر','Partner dashboard')}</Link></div></div><img src="/images/digzoom/creator-partner-live.webp" alt={t('صناعة منتج رقمي','Creating a digital product')} className="aspect-[16/10] w-full rounded-2xl object-cover"/></div></section>
 <section id="apply" className="scroll-mt-24 py-10 sm:py-14"><div className="mx-auto max-w-3xl px-4 sm:px-6"><form key={user?.id||'visitor'} onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><h2 className="text-2xl font-black">{t('بياناتك ومنتجك','You and your product')}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{t('اختر نوع المنتج وارفع ملفات المعاينة مباشرة من جهازك.','Choose a product type and upload preview files directly from your device.')}</p>{!user&&<p className="mt-4 rounded-xl bg-blue-50 p-4 text-sm font-bold text-blue-700"><Link to="/login">{t('سجّل الدخول أو أنشئ حسابًا لرفع الملفات وتقديم الطلب.','Sign in or create an account to upload files and apply.')}</Link></p>}
 {user&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><span>{t('أنت مسجّل بحساب:','Signed in as:')} <b dir="ltr">{user.email}</b></span><button type="button" disabled={sending||uploading} onClick={async()=>{await logout();setFiles([]);setNotice(undefined);}} className="font-bold text-blue-700 underline underline-offset-4 disabled:opacity-50">{t('تغيير الحساب','Switch account')}</button></div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label={t('الاسم الكامل','Full name')}><input name="name" required maxLength={100} defaultValue={user?.name||''}/></Field><Field label={t('البريد الإلكتروني للتواصل','Contact email')}><input name="email" type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)} autoComplete="email" maxLength={254} required dir="ltr"/><span className="mt-1 block text-xs font-normal leading-5 text-slate-500">{t('تقدر تعدّله للتواصل بخصوص طلبك؛ إيميل تسجيل الدخول يبقى كما هو.','You can change this for application updates; your sign-in email stays the same.')}</span></Field><Field label={t('رقم الجوال','Phone')}><input name="phone" required maxLength={30} dir="ltr"/></Field><Field label={t('اسم متجرك — اختياري','Store name — optional')}><input name="brand" maxLength={120}/></Field><Field label={t('نوع المنتج','Product type')}><select name="product_type" required defaultValue=""><option value="" disabled>{t('اختر نوع المنتج','Choose product type')}</option>{PRODUCT_KINDS.map(kind=><option key={kind.value} value={kind.value}>{ar?kind.ar:kind.en}</option>)}</select></Field><Field label={t('السعر المقترح بالريال — اختياري','Suggested price in SAR — optional')}><input name="suggested_price" type="number" min={0} max={100000}/></Field><Field label={t('اسم المنتج','Product name')} wide><input name="product_title" required minLength={3} maxLength={180}/></Field><Field label={t('وصف مختصر للمنتج','Short product description')} wide><textarea name="description" required rows={3} maxLength={2000}/></Field></div>
 <div className="mt-5"><PreviewFiles value={files} onChange={setFiles} onBusy={setUploading} disabled={!user||sending} ar={ar}/></div><div className="mt-5"><PartnerTerms ar={ar}/></div><label className="mt-4 flex items-start gap-3 text-sm leading-6 text-slate-600"><input type="checkbox" name="rights_confirmed" value="true" required className="mt-1 h-4 w-4 shrink-0"/>{t('أملك حقوق بيع هذا المنتج، وأوافق على شروط الشراكة والبيع.','I own the selling rights and accept the partnership and selling terms.')}</label>{notice&&<p role="status" className={`mt-4 rounded-xl p-4 text-sm ${notice.ok?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{notice.text}</p>}<button disabled={sending||uploading||!user} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-black text-white disabled:opacity-50">{sending?<Loader2 size={18} className="animate-spin"/>:<UploadCloud size={18}/>} {sending?t('جارٍ الإرسال…','Sending…'):uploading?t('انتظر اكتمال رفع الملفات','Wait for uploads to finish'):t('إرسال للمراجعة','Submit for review')}</button></form></div></section></main>;
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={`text-sm font-bold text-slate-700 ${wide?'sm:col-span-2':''}`}><span>{label}</span><div className="mt-2 [&>input]:min-h-12 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-slate-200 [&>input]:px-3 [&>select]:min-h-12 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-slate-200 [&>select]:px-3 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-slate-200 [&>textarea]:p-3">{children}</div></label>;}
