import {AssetPreview} from './PreviewFiles';
import {PRODUCT_KINDS} from '@/data/partnerFiles';
import {useEffect,useState,type FormEvent} from 'react';
import {merchantApi,money,partnerStatus} from '@/lib/merchant-api';
export default function AdminPartners(){
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setData(await merchantApi(undefined,true));}catch(e:any){setError(e.message);}}
 useEffect(()=>{void load();},[]);
 async function act(body:any){setBusy(true);setError('');try{await merchantApi(body,true);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const box='rounded-2xl border border-white/10 bg-[#131722] p-4 sm:p-6';
 const button='rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40';
 const input='w-full rounded-lg border border-white/15 bg-slate-900 p-3 text-white';
 const merchantName=(id:string)=>data?.merchants.find((m:any)=>m.id===id)?.name||id;
 if(!data)return <p role="status">{error||'جارٍ تحميل الشركاء…'}</p>;
 return <div dir="rtl" className="space-y-6"><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-black">شركاء DigZoom</h2><button className={button} onClick={load}>تحديث</button></div><p className="text-sm leading-7 text-slate-400">هوية التاجر داخلية. الزائر يشاهد DigZoom فقط. عمولة 15% لإحالة التاجر و25% لطلبات الموقع، بعد رسوم الدفع الفعلية. ميزانية التسويق المقترحة لا تتجاوز 10% من البيع وتُموّل من حصة الموقع.</p>{error&&<p role="alert" className="rounded-xl bg-red-500/10 p-4 text-red-300">{error}</p>}
 <section className={box}><h3 className="text-lg font-bold">طلبات الانضمام</h3><div className="mt-4 space-y-4">{!data.applications.length&&<p className="text-slate-400">لا توجد طلبات.</p>}{data.applications.map((a:any)=><article key={a.id} className="rounded-xl border border-white/10 p-4"><h4 className="font-bold">{a.name} {a.brand&&`· ${a.brand}`}</h4><p dir="ltr" className="mt-2 break-all text-sm text-slate-400">{a.email}</p><p className="mt-3 text-sm">{PRODUCT_KINDS.find(k=>k.value===a.product_type)?.ar||a.product_type} · {partnerStatus[a.status]||a.status}</p><p className="mt-3 whitespace-pre-wrap text-sm text-slate-300">{a.description}</p>{a.product_title&&<p className="mt-3 font-bold">{a.product_title}</p>}{(a.preview_asset_ids||[]).map((id:string)=><div key={id} className="mt-3 rounded-xl bg-white/5 p-3"><AssetPreview asset={{id,name:'ملف معاينة المنتج',mime_type:'',size_bytes:0}}/></div>)}{a.preview_url&&<a href={a.preview_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-blue-400">رابط المعاينة</a>}{a.status==='new'&&<div className="mt-4 flex flex-wrap gap-3"><button disabled={busy||!a.user_id||a.terms_version!=='2026-10-v1'} onClick={()=>act({action:'approve_application',id:a.id})} className={button}>اعتماد حساب التاجر</button><button disabled={busy} onClick={()=>act({action:'reject_application',id:a.id})} className="rounded-lg border border-red-500/30 px-4 py-2 text-red-300">رفض</button>{(!a.user_id||!a.terms_version)&&<p className="w-full text-xs text-amber-300">طلب قديم: يلزم إعادة التقديم بعد الدخول والموافقة على الشروط.</p>}</div>}</article>)}</div></section>
 <section className={box}><h3 className="text-lg font-bold">عروض التجار</h3><div className="mt-4 space-y-4">{!data.offers.length&&<p className="text-slate-400">لا توجد عروض.</p>}{data.offers.map((o:any)=><article key={o.id} className="rounded-xl border border-white/10 p-4"><div className="flex gap-4"><img src={o.image_url} className="h-20 w-20 rounded-lg object-cover" alt=""/><div><h4 className="font-bold">{o.title}</h4><p className="mt-2 text-sm text-slate-400">التاجر: {merchantName(o.merchant_id)} · {money(o.price_sar*100)} · {partnerStatus[o.status]}</p></div></div><p className="mt-4 whitespace-pre-wrap text-sm text-slate-300">{o.description}</p><p className="mt-3 text-sm text-amber-200">التسليم: {o.fulfillment_method}</p>{(o.preview_asset_ids||[]).map((id:string)=><div key={id} className="mt-3 rounded-xl bg-white/5 p-3"><AssetPreview asset={{id,name:'ملف معاينة المنتج',mime_type:'',size_bytes:0}}/></div>)}{o.preview_url&&<a className="mt-3 inline-block text-blue-400" href={o.preview_url} target="_blank" rel="noreferrer">معاينة المنتج</a>}{o.status==='review'&&<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'publish_offer',id:o.id,category_id:Number(f.get('category_id'))});}}><select name="category_id" required defaultValue="" className={input}><option value="" disabled>اختر تصنيف المنتج</option>{['جرافيكس','خطوط','قوالب','فيديوهات','كتب إلكترونية','صوتيات','أكواد','تصميم ويب','نماذج 3D','صور'].map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" required/>راجعت الحقوق والمحتوى وطريقة التسليم</label><button disabled={busy} className={button}>اعتماد ونشر باسم DigZoom</button><button disabled={busy} type="button" onClick={()=>{const note=window.prompt('سبب الرفض أو التعديل المطلوب');if(note)void act({action:'reject_offer',id:o.id,note});}} className="rounded-lg border border-red-500/30 px-4 py-2 text-red-300">رفض مع ملاحظة</button></form>}</article>)}</div></section>
 <section className={box}><h3 className="text-lg font-bold">التسليم والطلبات</h3><div className="mt-4 space-y-4">{!data.items.length&&<p className="text-slate-400">لا توجد طلبات شركاء.</p>}{data.items.map((i:any)=><article key={i.id} className="rounded-xl border border-white/10 p-4"><h4 className="font-bold">{i.product_title} × {i.quantity}</h4><p className="mt-2 text-sm text-slate-400">{merchantName(i.merchant_id)} · {partnerStatus[i.status]} · {i.commission_percent}%</p><p dir="ltr" className="mt-2 break-all text-xs text-slate-400">{i.order_id}</p><p className="mt-3 text-sm">بيع {money(i.gross_cents)} · رسوم {money(i.stripe_fee_cents)} · عمولة {money(i.commission_cents)} · مستحق {money(i.merchant_cents)}</p>{i.hold_reason&&<p className="mt-3 text-amber-300">{i.hold_reason} — لا تُصرف حتى مراجعة الاسترجاع/النزاع.</p>}{i.fulfillment_note&&<div className="mt-3 rounded-xl bg-white/5 p-3"><p className="whitespace-pre-wrap break-words text-sm">{i.fulfillment_note}</p>{!i.delivered_at&&<button disabled={busy||i.status==='held'} onClick={()=>act({action:'approve_delivery',id:i.id})} className={`${button} mt-3`}>اعتماد إثبات التسليم</button>}</div>}</article>)}</div></section>
 <section className={box}><h3 className="text-lg font-bold">التجار والتسوية اليدوية</h3><p className="mt-3 text-sm leading-7 text-slate-400">تحقّق من أهلية المستحقات، ونفّذ التحويل البنكي خارج الموقع، ثم سجّله بالمرجع والرسوم الفعلية. لا ينفّذ هذا النظام تحويلًا بنكيًا تلقائيًا.</p><div className="mt-5 space-y-4">{!data.merchants.length&&<p className="text-slate-400">لم يُعتمد تجار بعد.</p>}{data.merchants.map((m:any)=>{const eligible=data.items.filter((i:any)=>i.merchant_id===m.id&&i.status==='ready'&&i.delivered_at&&new Date(i.ready_at).getTime()<=Date.now());const gross=eligible.reduce((s:number,i:any)=>s+Number(i.merchant_cents||0),0);const held=data.items.some((i:any)=>i.merchant_id===m.id&&i.status==='held');return <article key={m.id} className="rounded-xl border border-white/10 p-4"><h4 className="font-bold">{m.name} · {partnerStatus[m.status]}</h4><p dir="ltr" className="mt-2 text-sm text-slate-400">{m.email}</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} className={button} onClick={()=>act({action:'sync_fees',merchant_id:m.id})}>تحقق من Stripe والرسوم</button><button disabled={busy} className="rounded-lg border px-4 py-2 text-sm" onClick={()=>act({action:'merchant_status',id:m.id,status:m.status==='active'?'suspended':'active'})}>{m.status==='active'?'إيقاف التاجر وعروضه':'إعادة التفعيل'}</button></div><p className="mt-4 font-bold">المؤهل: {money(gross)}</p>{held&&<p className="mt-3 text-amber-300">يوجد استرجاع/نزاع معلّق؛ التسوية متوقفة حتى مراجعته.</p>}<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'settle',merchant_id:m.id,reference:f.get('reference'),transfer_fee_cents:Math.round(Number(f.get('fee'))*100),expected_gross_cents:gross});}}><label className="text-sm">رسوم البنك/السحب الفعلية بالريال<input name="fee" type="number" step="0.01" min="0" required className={`${input} mt-2`}/></label><label className="text-sm">مرجع التحويل<input name="reference" required minLength={4} maxLength={200} className={`${input} mt-2`}/></label><label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required className="mt-1"/>تحققت من Stripe وأتممت التحويل للصافي بعد الرسوم، وأملك إثبات التحويل.</label><button disabled={busy||held||m.status!=='active'||gross<data.settings.minimum_payout_cents} className={button}>تسجيل التحويل المنفّذ</button></form></article>;})}</div></section>
 <section className={box}><h3 className="text-lg font-bold">سياسة التسوية</h3><form className="mt-4 flex flex-wrap items-end gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'settings',minimum_payout_cents:Math.round(Number(f.get('minimum'))*100),hold_days:Number(f.get('days'))});}}><label className="text-sm">الحد الأدنى بالريال<input name="minimum" type="number" min={100} required defaultValue={data.settings.minimum_payout_cents/100} className={`${input} mt-2`}/></label><label className="text-sm">مدة الانتظار بالأيام<input name="days" type="number" min={7} max={90} required defaultValue={data.settings.hold_days} className={`${input} mt-2`}/></label><button disabled={busy} className={button}>حفظ السياسة</button></form></section>
 <section className={box}><h3 className="text-lg font-bold">سجل التحويلات</h3>{!data.settlements.length&&<p className="mt-4 text-slate-400">لا توجد تحويلات مسجلة.</p>}{data.settlements.map((s:any)=><div key={s.id} className="mt-4 rounded-lg border border-white/10 p-4"><p>{merchantName(s.merchant_id)} · {money(s.paid_cents)} بعد رسوم {money(s.transfer_fee_cents)}</p><p className="mt-2 break-all text-sm text-slate-400">{s.reference} · {new Date(s.created_at).toLocaleDateString('ar-SA')}</p></div>)}</section>
 </div>;
}
