-- Migration: Audit logging + Product pricing + Tracking fields

-- 1. Add tracking fields to products
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS added_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS updated_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- 2. Add pricing/discount fields
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS original_price numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_percent int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_on_sale boolean DEFAULT false;

-- 3. Create admin activity logs table
CREATE TABLE IF NOT EXISTS admin_activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email text NOT NULL,
  admin_id uuid REFERENCES auth.users(id),
  action text NOT NULL, -- 'create_product', 'update_product', 'delete_product', 'toggle_product', 'upload_image'
  product_id bigint REFERENCES products(id),
  product_title text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz DEFAULT now()
);

-- 4. RLS for admin_activity_logs
ALTER TABLE admin_activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_activity_logs_select" ON admin_activity_logs
  FOR SELECT TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "admin_activity_logs_insert" ON admin_activity_logs
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

-- 5. Index for performance
CREATE INDEX IF NOT EXISTS idx_admin_logs_admin_id ON admin_activity_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_logs_product_id ON admin_activity_logs(product_id);
CREATE INDEX IF NOT EXISTS idx_admin_logs_created_at ON admin_activity_logs(created_at DESC);

-- 6. Update existing products: set original_price = price where original_price is 0
UPDATE products SET original_price = price WHERE original_price = 0 OR original_price IS NULL;
