-- ============================================
-- Fill title_en for ALL products that don't have it yet
-- Strategy: descriptive English names based on Arabic content
-- ============================================

-- First: show how many products are missing English titles
SELECT COUNT(*) as missing_en_count FROM products WHERE title_en IS NULL OR title_en = '';

-- ============================================
-- Batch 1: Products that already have manual translations (keep them)
-- ============================================

-- ============================================
-- Batch 2: Generic translations based on keyword matching
-- ============================================

UPDATE products SET title_en = 'Complete Digital Design Encyclopedia', description_en = 'Comprehensive digital design collection with premium resources', long_description_en = 'Comprehensive digital design collection with premium resources. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تصاميم%شاملة%';
UPDATE products SET title_en = 'Creative Design Library 2024', description_en = 'Latest creative design assets for professionals', long_description_en = 'Latest creative design assets for professionals. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تصاميم%2024%';
UPDATE products SET title_en = 'Complete Social Media Guide', description_en = 'Full social media marketing strategy guide', long_description_en = 'Full social media marketing strategy guide. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%سوشيال%ميديا%شامل%';
UPDATE products SET title_en = 'Digital Marketing Masterclass', description_en = 'Complete digital marketing course from beginner to expert', long_description_en = 'Complete digital marketing course from beginner to expert. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%دورة%تسويق%رقمي%';
UPDATE products SET title_en = 'Motion Graphics Templates Pack', description_en = 'Professional motion graphics templates for video editors', long_description_en = 'Professional motion graphics templates for video editors. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%موشن%جرافيك%';
UPDATE products SET title_en = 'Professional Sound Effects Library', description_en = 'High-quality sound effects for video and game production', long_description_en = 'High-quality sound effects for video and game production. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مؤثرات%صوتية%احترافية%';
UPDATE products SET title_en = 'Background Music Collection for Videos', description_en = 'Royalty-free background music for content creators', long_description_en = 'Royalty-free background music for content creators. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%موسيقى%خلفية%';
UPDATE products SET title_en = 'E-Commerce Business Guide', description_en = 'Step-by-step guide to building an online business', long_description_en = 'Step-by-step guide to building an online business. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تجارة%إلكترونية%';
UPDATE products SET title_en = 'Professional Photography Course', description_en = 'Master photography from basics to professional techniques', long_description_en = 'Master photography from basics to professional techniques. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تصوير%احترافي%دورة%';
UPDATE products SET title_en = 'PowerPoint Presentation Templates', description_en = 'Premium PowerPoint templates for business presentations', long_description_en = 'Premium PowerPoint templates for business presentations. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%بوربوينت%قوالب%';
UPDATE products SET title_en = 'SEO Optimization Guide 2025', description_en = 'Latest search engine optimization strategies and techniques', long_description_en = 'Latest search engine optimization strategies and techniques. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%SEO%تحسين%محركات%';
UPDATE products SET title_en = 'Graphic Design Master Course', description_en = 'Complete graphic design course with practical projects', long_description_en = 'Complete graphic design course with practical projects. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%جرافيك%ديزاين%دورة%';
UPDATE products SET title_en = 'Icons & Logos Design Library', description_en = 'Professional icons and logo templates for branding', long_description_en = 'Professional icons and logo templates for branding. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%أيقونات%شعارات%';
UPDATE products SET title_en = 'TikTok Growth Strategy Guide', description_en = 'How to grow your TikTok account from zero to viral', long_description_en = 'How to grow your TikTok account from zero to viral. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تيك%توك%دليل%';
UPDATE products SET title_en = 'Vectors & Illustrations Collection', description_en = 'High-quality vector illustrations for designers', long_description_en = 'High-quality vector illustrations for designers. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فيكتور%رسومات%مكتبة%';
UPDATE products SET title_en = 'Podcasting Masterclass', description_en = 'Learn to create, record, and monetize podcasts', long_description_en = 'Learn to create, record, and monetize podcasts. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%بودكاست%دورة%';
UPDATE products SET title_en = 'Instagram Templates Pack', description_en = 'Ready-to-use Instagram post and story templates', long_description_en = 'Ready-to-use Instagram post and story templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إنستغرام%قوالب%';
UPDATE products SET title_en = 'YouTube Channel Growth Guide', description_en = 'Strategies to grow your YouTube channel and monetize', long_description_en = 'Strategies to grow your YouTube channel and monetize. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%يوتيوب%دليل%';
UPDATE products SET title_en = 'Arabic Fonts Collection', description_en = 'Premium Arabic fonts for designers and content creators', long_description_en = 'Premium Arabic fonts for designers and content creators. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%خطوط%عربية%';
UPDATE products SET title_en = 'Web Development Complete Course', description_en = 'Full-stack web development from HTML to deployment', long_description_en = 'Full-stack web development from HTML to deployment. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تطوير%ويب%دورة%';
UPDATE products SET title_en = 'Mobile App Design Templates', description_en = 'UI/UX design templates for iOS and Android apps', long_description_en = 'UI/UX design templates for iOS and Android apps. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تطبيقات%موبايل%تصميم%';
UPDATE products SET title_en = 'Email Marketing Automation Guide', description_en = 'Build and automate email marketing campaigns that convert', long_description_en = 'Build and automate email marketing campaigns that convert. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إيميل%تسويق%أتمتة%';
UPDATE products SET title_en = 'Content Creation Strategy', description_en = 'Create engaging content for all social media platforms', long_description_en = 'Create engaging content for all social media platforms. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%محتوى%استراتيجية%إنشاء%';
UPDATE products SET title_en = 'Brand Identity Design Kit', description_en = 'Complete branding kit with logos, colors, and guidelines', long_description_en = 'Complete branding kit with logos, colors, and guidelines. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%هوية%بصرية%براند%';
UPDATE products SET title_en = 'Video Editing Templates', description_en = 'Professional video editing templates for Premiere and After Effects', long_description_en = 'Professional video editing templates for Premiere and After Effects. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مونتاج%فيديو%قوالب%';
UPDATE products SET title_en = '3D Models & Assets Library', description_en = 'High-quality 3D models for games and visualization', long_description_en = 'High-quality 3D models for games and visualization. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%3D%نماذج%مكتبة%';
UPDATE products SET title_en = 'Data Analytics Dashboard Templates', description_en = 'Ready-made dashboards for business intelligence', long_description_en = 'Ready-made dashboards for business intelligence. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تحليل%بيانات%dashboard%';
UPDATE products SET title_en = 'ChatGPT & AI Prompts Collection', description_en = '1000+ AI prompts for marketing, writing, and business', long_description_en = '1000+ AI prompts for marketing, writing, and business. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ChatGPT%ذكاء%اصطناعي%';
UPDATE products SET title_en = 'WordPress Theme Collection', description_en = 'Premium WordPress themes for any business type', long_description_en = 'Premium WordPress themes for any business type. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ووردبريس%قوالب%';
UPDATE products SET title_en = 'Print Design Templates', description_en = 'Business cards, flyers, brochures, and print-ready designs', long_description_en = 'Business cards, flyers, brochures, and print-ready designs. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%طباعة%تصاميم%مطبوعات%';
UPDATE products SET title_en = 'UI/UX Design System', description_en = 'Complete design system with components and style guide', long_description_en = 'Complete design system with components and style guide. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%UI%UX%تصميم%نظام%';
UPDATE products SET title_en = 'Cryptocurrency & NFT Guide', description_en = 'Understanding crypto, blockchain, and NFT trading', long_description_en = 'Understanding crypto, blockchain, and NFT trading. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%عملات%رقمية%كريبتو%';
UPDATE products SET title_en = 'Freelancing Success Blueprint', description_en = 'How to start and scale a profitable freelancing career', long_description_en = 'How to start and scale a profitable freelancing career. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فريلانس%عمل%حر%';
UPDATE products SET title_en = ' dropshipping Business Guide', description_en = 'Build a dropshipping business with zero inventory', long_description_en = 'Build a dropshipping business with zero inventory. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%دروب%شيبينج%تجارة%';
UPDATE products SET title_en = 'Affiliate Marketing Mastery', description_en = 'Earn passive income through affiliate marketing', long_description_en = 'Earn passive income through affiliate marketing. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%أفلييت%تسويق%بالعمولة%';
UPDATE products SET title_en = 'Facebook Ads Strategy Guide', description_en = 'Create high-converting Facebook ad campaigns', long_description_en = 'Create high-converting Facebook ad campaigns. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فيسبوك%إعلانات%دليل%';
UPDATE products SET title_en = 'Instagram Reels & Shorts Templates', description_en = 'Viral video templates for Instagram Reels and YouTube Shorts', long_description_en = 'Viral video templates for Instagram Reels and YouTube Shorts. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ريلز%ريلز%قوالب%';
UPDATE products SET title_en = 'SaaS Business Startup Kit', description_en = 'Build and launch your own software-as-a-service product', long_description_en = 'Build and launch your own software-as-a-service product. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%SaaS%برمجيات%خدمة%';
UPDATE products SET title_en = 'Customer Service Excellence Guide', description_en = 'Build a world-class customer support system', long_description_en = 'Build a world-class customer support system. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%خدمة%عملاء%دليل%';
UPDATE products SET title_en = 'Public Speaking & Presentation Skills', description_en = 'Master the art of public speaking and presentations', long_description_en = 'Master the art of public speaking and presentations. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تحدث%عام%مهارات%عرض%';
UPDATE products SET title_en = 'Resume & CV Design Templates', description_en = 'Stand out with professionally designed resume templates', long_description_en = 'Stand out with professionally designed resume templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%سيرة%ذاتية%قوالب%';
UPDATE products SET title_en = 'Virtual Assistant Business Kit', description_en = 'Start a profitable virtual assistant business from home', long_description_en = 'Start a profitable virtual assistant business from home. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مساعد%افتراضي%أعمال%';
UPDATE products SET title_en = 'Webinar & Online Course Creation', description_en = 'Create and sell online courses and webinars', long_description_en = 'Create and sell online courses and webinars. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%كورس%أونلاين%ويبينار%';
UPDATE products SET title_en = 'Customer Retention Strategies', description_en = 'Keep customers coming back with proven loyalty strategies', long_description_en = 'Keep customers coming back with proven loyalty strategies. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%استبقاء%عملاء%استراتيجية%';
UPDATE products SET title_en = 'Business Negotiation Tactics', description_en = 'Win every negotiation with advanced business tactics', long_description_en = 'Win every negotiation with advanced business tactics. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تفاوض%أعمال%مهارات%';
UPDATE products SET title_en = 'Productivity & Focus Mastery', description_en = 'Double your productivity with proven focus techniques', long_description_en = 'Double your productivity with proven focus techniques. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إنتاجية%تركيز%تقنيات%';
UPDATE products SET title_en = 'HR & Team Management Guide', description_en = 'Build and manage high-performing remote teams', long_description_en = 'Build and manage high-performing remote teams. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%موارد%بشرية%فريق%';
UPDATE products SET title_en = 'Legal Contracts & Agreement Templates', description_en = 'Professional legal templates for business contracts', long_description_en = 'Professional legal templates for business contracts. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%عقود%قانونية%نماذج%';
UPDATE products SET title_en = 'Tax Planning for Entrepreneurs', description_en = 'Optimize your taxes and keep more of your earnings', long_description_en = 'Optimize your taxes and keep more of your earnings. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ضرائب%تخطيط%ريادي%';
UPDATE products SET title_en = 'Crowdfunding Campaign Guide', description_en = 'Launch successful crowdfunding campaigns for any project', long_description_en = 'Launch successful crowdfunding campaigns for any project. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تمويل%جماعي%حملة%';
UPDATE products SET title_en = 'AI Image Generation Prompts', description_en = 'Master Midjourney, DALL-E, and Stable Diffusion prompts', long_description_en = 'Master Midjourney, DALL-E, and Stable Diffusion prompts. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%AI%صور%توليد%برومبت%';
UPDATE products SET title_en = 'CRM & Sales Pipeline Templates', description_en = 'Manage leads and close more deals with CRM templates', long_description_en = 'Manage leads and close more deals with CRM templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%CRM%مبيعات%قوالب%';
UPDATE products SET title_en = 'Market Research & Analysis Toolkit', description_en = 'Conduct professional market research for any industry', long_description_en = 'Conduct professional market research for any industry. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%بحث%سوق%تحليل%';
UPDATE products SET title_en = 'Personal Finance & Investment Guide', description_en = 'Take control of your finances and build long-term wealth', long_description_en = 'Take control of your finances and build long-term wealth. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مالية%شخصية%استثمار%';
UPDATE products SET title_en = 'Startup Funding & Pitch Deck Templates', description_en = 'Create pitch decks that impress investors and secure funding', long_description_en = 'Create pitch decks that impress investors and secure funding. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تمويل%ستارت%اب%عرض%';
UPDATE products SET title_en = 'Etsy & Amazon FBA Starter Kit', description_en = 'Launch and scale your e-commerce store on Etsy or Amazon', long_description_en = 'Launch and scale your e-commerce store on Etsy or Amazon. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إيتسي%أمازون%FBA%';
UPDATE products SET title_en = 'Lead Generation Machine', description_en = 'Build automated systems to generate qualified leads daily', long_description_en = 'Build automated systems to generate qualified leads daily. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%جذب%عملاء%محتملين%نظام%';
UPDATE products SET title_en = 'Online Community Building Guide', description_en = 'Create and grow engaged online communities', long_description_en = 'Create and grow engaged online communities. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مجتمع%أونلاين%بناء%';
UPDATE products SET title_en = 'Event Planning & Management Templates', description_en = 'Plan professional events with ready-made templates', long_description_en = 'Plan professional events with ready-made templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فعاليات%تخطيط%إدارة%';
UPDATE products SET title_en = 'Press Release & Media Kit Templates', description_en = 'Get media coverage with professional press release templates', long_description_en = 'Get media coverage with professional press release templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%بيان%صحفي%إعلام%';
UPDATE products SET title_en = 'Business Partnership Agreement Templates', description_en = 'Protect your business with legally sound partnership contracts', long_description_en = 'Protect your business with legally sound partnership contracts. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%شراكة%أعمال%اتفاقية%';
UPDATE products SET title_en = 'Customer Journey Mapping Toolkit', description_en = 'Optimize every touchpoint of your customer experience', long_description_en = 'Optimize every touchpoint of your customer experience. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%رحلة%عميل%خريطة%';
UPDATE products SET title_en = 'Competitive Analysis Templates', description_en = 'Analyze your competitors and find your competitive edge', long_description_en = 'Analyze your competitors and find your competitive edge. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%منافسين%تحليل%نماذج%';
UPDATE products SET title_en = 'Subscription Business Model Guide', description_en = 'Build recurring revenue with subscription-based business models', long_description_en = 'Build recurring revenue with subscription-based business models. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%اشتراك%نموذج%أعمال%';
UPDATE products SET title_en = 'White Label Product Catalog', description_en = 'Rebrand and sell ready-made products as your own', long_description_en = 'Rebrand and sell ready-made products as your own. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%white%label%منتجات%جاهزة%';
UPDATE products SET title_en = 'Influencer Outreach Templates', description_en = 'Connect and collaborate with influencers in any niche', long_description_en = 'Connect and collaborate with influencers in any niche. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%انفلونسر%تواصل%قوالب%';
UPDATE products SET title_en = 'SMS Marketing Campaign Templates', description_en = 'High-converting SMS marketing templates and strategies', long_description_en = 'High-converting SMS marketing templates and strategies. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%SMS%رسائل%تسويق%';
UPDATE products SET title_en = 'Referral Program Blueprint', description_en = 'Turn customers into brand advocates with referral systems', long_description_en = 'Turn customers into brand advocates with referral systems. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إحالة%برنامج%عملاء%';
UPDATE products SET title_en = 'Google Analytics 4 Mastery Guide', description_en = 'Track, measure, and optimize with GA4 and data-driven decisions', long_description_en = 'Track, measure, and optimize with GA4 and data-driven decisions. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%جوجل%أناليتكس%4%';
UPDATE products SET title_en = 'B2B Sales Strategy Playbook', description_en = 'Close enterprise deals with proven B2B sales techniques', long_description_en = 'Close enterprise deals with proven B2B sales techniques. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%B2B%مبيعات%شركات%';
UPDATE products SET title_en = 'Crisis Management & PR Guide', description_en = 'Handle business crises and protect your brand reputation', long_description_en = 'Handle business crises and protect your brand reputation. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%أزمات%إدارة%سمعة%';
UPDATE products SET title_en = 'Mobile-First Design Templates', description_en = 'Design beautiful mobile experiences that convert visitors', long_description_en = 'Design beautiful mobile experiences that convert visitors. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%موبايل%تصميم%جوال%';
UPDATE products SET title_en = 'Accessibility & Inclusive Design Kit', description_en = 'Create accessible digital products for all users', long_description_en = 'Create accessible digital products for all users. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إتاحة%تصميم%شامل%';
UPDATE products SET title_en = 'Growth Hacking Experiments Log', description_en = 'Run systematic growth experiments to scale your business', long_description_en = 'Run systematic growth experiments to scale your business. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%نمو%تجارب%growth%hacking%';
UPDATE products SET title_en = 'Customer Testimonial Collection Templates', description_en = 'Collect and showcase powerful customer testimonials', long_description_en = 'Collect and showcase powerful customer testimonials. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%شهادات%عملاء%توصيات%';
UPDATE products SET title_en = 'Supply Chain Management Toolkit', description_en = 'Optimize your supply chain for efficiency and cost reduction', long_description_en = 'Optimize your supply chain for efficiency and cost reduction. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%سلسلة%إمداد%إدارة%';
UPDATE products SET title_en = 'Quality Assurance & Testing Templates', description_en = 'Ensure product quality with professional QA templates', long_description_en = 'Ensure product quality with professional QA templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%جودة%ضمان%اختبار%';
UPDATE products SET title_en = 'Employee Onboarding & Training Kit', description_en = 'Onboard new hires efficiently with structured training programs', long_description_en = 'Onboard new hires efficiently with structured training programs. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%موظفين%تدريب%انضمام%';
UPDATE products SET title_en = 'API Documentation Templates', description_en = 'Create clear and comprehensive API documentation', long_description_en = 'Create clear and comprehensive API documentation. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%API%توثيق%واجهة%برمجة%';
UPDATE products SET title_en = 'Data Privacy & GDPR Compliance Guide', description_en = 'Stay compliant with data privacy laws and protect user data', long_description_en = 'Stay compliant with data privacy laws and protect user data. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%خصوصية%بيانات%GDPR%';
UPDATE products SET title_en = 'Exit Strategy & Business Valuation Guide', description_en = 'Plan your exit and maximize your business valuation', long_description_en = 'Plan your exit and maximize your business valuation. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%خروج%تقييم%أعمال%';
UPDATE products SET title_en = 'Innovation & Brainstorming Workshop Kit', description_en = 'Foster innovation with structured brainstorming sessions', long_description_en = 'Foster innovation with structured brainstorming sessions. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ابتكار%عصف%ذهني%ورشة%';
UPDATE products SET title_en = 'Customer Feedback Loop System', description_en = 'Build systems to collect and act on customer feedback', long_description_en = 'Build systems to collect and act on customer feedback. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ملاحظات%عملاء%نظام%';
UPDATE products SET title_en = 'Micro-SaaS Validation Playbook', description_en = 'Validate your micro-SaaS idea before writing a single line of code', long_description_en = 'Validate your micro-SaaS idea before writing a single line of code. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مايكرو%SaaS%تحقق%';
UPDATE products SET title_en = 'No-Code App Building Guide', description_en = 'Build apps without coding using Bubble, Webflow, and Zapier', long_description_en = 'Build apps without coding using Bubble, Webflow, and Zapier. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%no-code%بدون%برمجة%';
UPDATE products SET title_en = 'Sales Funnel Design Templates', description_en = 'Design high-converting sales funnels for any product or service', long_description_en = 'Design high-converting sales funnels for any product or service. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%funnel%مبيعات%قمع%';
UPDATE products SET title_en = 'Loyalty Program Design Kit', description_en = 'Create loyalty programs that keep customers coming back', long_description_en = 'Create loyalty programs that keep customers coming back. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%ولاء%برنامج%عملاء%';
UPDATE products SET title_en = 'Podcast Monetization Blueprint', description_en = 'Turn your podcast into a revenue-generating machine', long_description_en = 'Turn your podcast into a revenue-generating machine. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%بودكاست%ربح%تدفق%';
UPDATE products SET title_en = 'Web Design Trends & Inspiration 2025', description_en = 'Stay ahead with the latest web design trends and inspiration', long_description_en = 'Stay ahead with the latest web design trends and inspiration. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تصميم%ويب%توجهات%2025%';
UPDATE products SET title_en = 'Brand Voice & Messaging Framework', description_en = 'Develop a consistent brand voice that resonates with your audience', long_description_en = 'Develop a consistent brand voice that resonates with your audience. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%صوت%علامة%رسالة%';
UPDATE products SET title_en = 'LinkedIn Growth & Lead Generation Guide', description_en = 'Grow your LinkedIn presence and generate B2B leads', long_description_en = 'Grow your LinkedIn presence and generate B2B leads. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%لينكدإن%LinkedIn%نمو%';
UPDATE products SET title_en = 'Product Launch Checklist & Templates', description_en = 'Launch products successfully with a proven checklist system', long_description_en = 'Launch products successfully with a proven checklist system. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إطلاق%منتج%قائمة%تحقق%';
UPDATE products SET title_en = 'Customer Success Playbook', description_en = 'Ensure customers achieve their goals and stay subscribed', long_description_en = 'Ensure customers achieve their goals and stay subscribed. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%نجاح%عملاء%success%';
UPDATE products SET title_en = 'Web Security & SSL Implementation Guide', description_en = 'Secure your website with SSL, firewalls, and best practices', long_description_en = 'Secure your website with SSL, firewalls, and best practices. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%أمان%موقع%SSL%';
UPDATE products SET title_en = 'User Persona & Avatar Templates', description_en = 'Create detailed user personas for better marketing targeting', long_description_en = 'Create detailed user personas for better marketing targeting. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%شخصية%مستخدم%avatar%';
UPDATE products SET title_en = 'Landing Page Optimization Toolkit', description_en = 'Optimize landing pages for maximum conversion rates', long_description_en = 'Optimize landing pages for maximum conversion rates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%landing%page%تحسين%';
UPDATE products SET title_en = 'A/B Testing Framework & Templates', description_en = 'Run statistically valid A/B tests to improve conversions', long_description_en = 'Run statistically valid A/B tests to improve conversions. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%A/B%testing%اختبار%';
UPDATE products SET title_en = 'E-Commerce Analytics Dashboard', description_en = 'Track key metrics and make data-driven business decisions', long_description_en = 'Track key metrics and make data-driven business decisions. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%تجارة%إلكترونية%تحليلات%dashboard%';
UPDATE products SET title_en = 'Influencer Contract & Rate Card Templates', description_en = 'Negotiate and manage influencer partnerships professionally', long_description_en = 'Negotiate and manage influencer partnerships professionally. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%انفلونسر%عقد%أسعار%';
UPDATE products SET title_en = 'Community Moderation & Management Guide', description_en = 'Build healthy online communities with effective moderation', long_description_en = 'Build healthy online communities with effective moderation. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%إدارة%مجتمع%إشراف%';
UPDATE products SET title_en = 'Brand Ambassador Program Kit', description_en = 'Launch a brand ambassador program that drives word-of-mouth', long_description_en = 'Launch a brand ambassador program that drives word-of-mouth. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%سفير%علامة%برنامج%';
UPDATE products SET title_en = 'Video Testimonial Recording Guide', description_en = 'Collect powerful video testimonials from your best customers', long_description_en = 'Collect powerful video testimonials from your best customers. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فيديو%توصية%شهادة%عميل%';
UPDATE products SET title_en = 'Remote Work Policy Templates', description_en = 'Create effective remote work policies for distributed teams', long_description_en = 'Create effective remote work policies for distributed teams. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%عمل%بعد%عن%بعد%سياسات%';
UPDATE products SET title_en = 'Inventory Management System Templates', description_en = 'Track and manage inventory with professional system templates', long_description_en = 'Track and manage inventory with professional system templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%مخزون%إدارة%نظام%جرد%';
UPDATE products SET title_en = 'Customer Churn Prevention Playbook', description_en = 'Identify at-risk customers and prevent churn before it happens', long_description_en = 'Identify at-risk customers and prevent churn before it happens. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%فقد%عملاء%churn%retention%';
UPDATE products SET title_en = 'Partnership Proposal Templates', description_en = 'Win strategic partnerships with professional proposal templates', long_description_en = 'Win strategic partnerships with professional proposal templates. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%شراكة%اقتراح%عرض%تقديمي%';
UPDATE products SET title_en = 'Merger & Acquisition Due Diligence Checklist', description_en = 'Conduct thorough due diligence for M&A transactions', long_description_en = 'Conduct thorough due diligence for M&A transactions. Includes all files with user guide and premium support.' WHERE title_en IS NULL AND title LIKE '%اندماج%استحواذ%due%diligence%';

-- ============================================
-- Final catch-all: For any remaining products without title_en
-- Set a professional English placeholder
-- ============================================

UPDATE products SET title_en = 'Premium Digital Product', description_en = 'High-quality digital resource for professionals' WHERE title_en IS NULL;
UPDATE products SET title_en = title WHERE title_en = 'Premium Digital Product' AND title LIKE '%[AR]%';

-- Final verification: count products with and without English titles
SELECT 
  COUNT(*) as total_products,
  COUNT(title_en) as with_english,
  COUNT(*) - COUNT(title_en) as missing_english
FROM products;
